
-- --------------------------------------------------------

--
-- Structure de la table `d8_url_alias`
--

DROP TABLE IF EXISTS `d8_url_alias`;
CREATE TABLE IF NOT EXISTS `d8_url_alias` (
  `pid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'A unique path alias identifier.',
  `source` varchar(255) NOT NULL DEFAULT '' COMMENT 'The Drupal path this alias is for. e.g. node/12.',
  `alias` varchar(255) NOT NULL DEFAULT '' COMMENT 'The alias for this path. e.g. title-of-the-story.',
  `langcode` varchar(12) CHARACTER SET ascii NOT NULL DEFAULT '' COMMENT 'The language code this alias is for. if ''und'', the alias will be used for unknown languages. Each Drupal path can have an alias for each supported language.',
  PRIMARY KEY (`pid`),
  KEY `alias_langcode_pid` (`alias`(191),`langcode`,`pid`),
  KEY `source_langcode_pid` (`source`(191),`langcode`,`pid`)
) ENGINE=InnoDB AUTO_INCREMENT=117 DEFAULT CHARSET=utf8mb4 COMMENT='A list of URL aliases for Drupal paths. a user may visit…';

--
-- Déchargement des données de la table `d8_url_alias`
--

INSERT INTO `d8_url_alias` (`pid`, `source`, `alias`, `langcode`) VALUES
(1, '/node/1', '/qui-sommes-nous', 'en'),
(2, '/node/2', '/conditions-generales-d-utilisation', 'en'),
(3, '/webform/contact', '/form/contact', 'en'),
(4, '/webform/contact', '/form/contact', 'und'),
(5, '/webform/contact/submissions', '/form/contact/submissions', 'en'),
(6, '/webform/contact/submissions', '/form/contact/submissions', 'und'),
(7, '/webform/contact/drafts', '/form/contact/drafts', 'en'),
(8, '/webform/contact/drafts', '/form/contact/drafts', 'und'),
(9, '/webform/contact/confirmation', '/form/contact/confirmation', 'en'),
(10, '/webform/contact/confirmation', '/form/contact/confirmation', 'und'),
(11, '/webform/template_user_profile', '/form/template-user-profile', 'en'),
(12, '/webform/template_user_profile', '/form/template-user-profile', 'und'),
(13, '/webform/template_user_profile/submissions', '/form/template-user-profile/submissions', 'en'),
(14, '/webform/template_user_profile/submissions', '/form/template-user-profile/submissions', 'und'),
(15, '/webform/template_user_profile/drafts', '/form/template-user-profile/drafts', 'en'),
(16, '/webform/template_user_profile/drafts', '/form/template-user-profile/drafts', 'und'),
(17, '/webform/template_user_profile/confirmation', '/form/template-user-profile/confirmation', 'en'),
(18, '/webform/template_user_profile/confirmation', '/form/template-user-profile/confirmation', 'und'),
(19, '/webform/template_subscribe', '/form/template-subscribe', 'en'),
(20, '/webform/template_subscribe', '/form/template-subscribe', 'und'),
(21, '/webform/template_subscribe/submissions', '/form/template-subscribe/submissions', 'en'),
(22, '/webform/template_subscribe/submissions', '/form/template-subscribe/submissions', 'und'),
(23, '/webform/template_subscribe/drafts', '/form/template-subscribe/drafts', 'en'),
(24, '/webform/template_subscribe/drafts', '/form/template-subscribe/drafts', 'und'),
(25, '/webform/template_subscribe/confirmation', '/form/template-subscribe/confirmation', 'en'),
(26, '/webform/template_subscribe/confirmation', '/form/template-subscribe/confirmation', 'und'),
(27, '/webform/template_session_evaluation', '/form/template-session-evaluation', 'en'),
(28, '/webform/template_session_evaluation', '/form/template-session-evaluation', 'und'),
(29, '/webform/template_session_evaluation/submissions', '/form/template-session-evaluation/submissions', 'en'),
(30, '/webform/template_session_evaluation/submissions', '/form/template-session-evaluation/submissions', 'und'),
(31, '/webform/template_session_evaluation/drafts', '/form/template-session-evaluation/drafts', 'en'),
(32, '/webform/template_session_evaluation/drafts', '/form/template-session-evaluation/drafts', 'und'),
(33, '/webform/template_session_evaluation/confirmation', '/form/template-session-evaluation/confirmation', 'en'),
(34, '/webform/template_session_evaluation/confirmation', '/form/template-session-evaluation/confirmation', 'und'),
(35, '/webform/template_registration', '/form/template-registration', 'en'),
(36, '/webform/template_registration', '/form/template-registration', 'und'),
(37, '/webform/template_registration/submissions', '/form/template-registration/submissions', 'en'),
(38, '/webform/template_registration/submissions', '/form/template-registration/submissions', 'und'),
(39, '/webform/template_registration/drafts', '/form/template-registration/drafts', 'en'),
(40, '/webform/template_registration/drafts', '/form/template-registration/drafts', 'und'),
(41, '/webform/template_registration/confirmation', '/form/template-registration/confirmation', 'en'),
(42, '/webform/template_registration/confirmation', '/form/template-registration/confirmation', 'und'),
(43, '/webform/template_job_seeker_profile', '/form/template-job-seeker-profile', 'en'),
(44, '/webform/template_job_seeker_profile', '/form/template-job-seeker-profile', 'und'),
(45, '/webform/template_job_seeker_profile/submissions', '/form/template-job-seeker-profile/submissions', 'en'),
(46, '/webform/template_job_seeker_profile/submissions', '/form/template-job-seeker-profile/submissions', 'und'),
(47, '/webform/template_job_seeker_profile/drafts', '/form/template-job-seeker-profile/drafts', 'en'),
(48, '/webform/template_job_seeker_profile/drafts', '/form/template-job-seeker-profile/drafts', 'und'),
(49, '/webform/template_job_seeker_profile/confirmation', '/form/template-job-seeker-profile/confirmation', 'en'),
(50, '/webform/template_job_seeker_profile/confirmation', '/form/template-job-seeker-profile/confirmation', 'und'),
(51, '/webform/template_job_application', '/form/template-job-application', 'en'),
(52, '/webform/template_job_application', '/form/template-job-application', 'und'),
(53, '/webform/template_job_application/submissions', '/form/template-job-application/submissions', 'en'),
(54, '/webform/template_job_application/submissions', '/form/template-job-application/submissions', 'und'),
(55, '/webform/template_job_application/drafts', '/form/template-job-application/drafts', 'en'),
(56, '/webform/template_job_application/drafts', '/form/template-job-application/drafts', 'und'),
(57, '/webform/template_job_application/confirmation', '/form/template-job-application/confirmation', 'en'),
(58, '/webform/template_job_application/confirmation', '/form/template-job-application/confirmation', 'und'),
(59, '/webform/template_issue', '/form/template-issue', 'en'),
(60, '/webform/template_issue', '/form/template-issue', 'und'),
(61, '/webform/template_issue/submissions', '/form/template-issue/submissions', 'en'),
(62, '/webform/template_issue/submissions', '/form/template-issue/submissions', 'und'),
(63, '/webform/template_issue/drafts', '/form/template-issue/drafts', 'en'),
(64, '/webform/template_issue/drafts', '/form/template-issue/drafts', 'und'),
(65, '/webform/template_issue/confirmation', '/form/template-issue/confirmation', 'en'),
(66, '/webform/template_issue/confirmation', '/form/template-issue/confirmation', 'und'),
(67, '/webform/template_feedback', '/form/template-feedback', 'en'),
(68, '/webform/template_feedback', '/form/template-feedback', 'und'),
(69, '/webform/template_feedback/submissions', '/form/template-feedback/submissions', 'en'),
(70, '/webform/template_feedback/submissions', '/form/template-feedback/submissions', 'und'),
(71, '/webform/template_feedback/drafts', '/form/template-feedback/drafts', 'en'),
(72, '/webform/template_feedback/drafts', '/form/template-feedback/drafts', 'und'),
(73, '/webform/template_feedback/confirmation', '/form/template-feedback/confirmation', 'en'),
(74, '/webform/template_feedback/confirmation', '/form/template-feedback/confirmation', 'und'),
(75, '/webform/template_employee_evaluation', '/form/template-employee-evaluation', 'en'),
(76, '/webform/template_employee_evaluation', '/form/template-employee-evaluation', 'und'),
(77, '/webform/template_employee_evaluation/submissions', '/form/template-employee-evaluation/submissions', 'en'),
(78, '/webform/template_employee_evaluation/submissions', '/form/template-employee-evaluation/submissions', 'und'),
(79, '/webform/template_employee_evaluation/drafts', '/form/template-employee-evaluation/drafts', 'en'),
(80, '/webform/template_employee_evaluation/drafts', '/form/template-employee-evaluation/drafts', 'und'),
(81, '/webform/template_employee_evaluation/confirmation', '/form/template-employee-evaluation/confirmation', 'en'),
(82, '/webform/template_employee_evaluation/confirmation', '/form/template-employee-evaluation/confirmation', 'und'),
(83, '/webform/template_donation', '/form/template-donation', 'en'),
(84, '/webform/template_donation', '/form/template-donation', 'und'),
(85, '/webform/template_donation/submissions', '/form/template-donation/submissions', 'en'),
(86, '/webform/template_donation/submissions', '/form/template-donation/submissions', 'und'),
(87, '/webform/template_donation/drafts', '/form/template-donation/drafts', 'en'),
(88, '/webform/template_donation/drafts', '/form/template-donation/drafts', 'und'),
(89, '/webform/template_donation/confirmation', '/form/template-donation/confirmation', 'en'),
(90, '/webform/template_donation/confirmation', '/form/template-donation/confirmation', 'und'),
(91, '/webform/template_contact', '/form/template-contact', 'en'),
(92, '/webform/template_contact', '/form/template-contact', 'und'),
(93, '/webform/template_contact/submissions', '/form/template-contact/submissions', 'en'),
(94, '/webform/template_contact/submissions', '/form/template-contact/submissions', 'und'),
(95, '/webform/template_contact/drafts', '/form/template-contact/drafts', 'en'),
(96, '/webform/template_contact/drafts', '/form/template-contact/drafts', 'und'),
(97, '/webform/template_contact/confirmation', '/form/template-contact/confirmation', 'en'),
(98, '/webform/template_contact/confirmation', '/form/template-contact/confirmation', 'und'),
(99, '/webform/reservation_de_table', '/form/reservation-de-table', 'en'),
(100, '/webform/reservation_de_table', '/form/reservation-de-table', 'und'),
(101, '/webform/reservation_de_table/submissions', '/form/reservation-de-table/submissions', 'en'),
(102, '/webform/reservation_de_table/submissions', '/form/reservation-de-table/submissions', 'und'),
(103, '/webform/reservation_de_table/drafts', '/form/reservation-de-table/drafts', 'en'),
(104, '/webform/reservation_de_table/drafts', '/form/reservation-de-table/drafts', 'und'),
(105, '/webform/reservation_de_table/confirmation', '/form/reservation-de-table/confirmation', 'en'),
(106, '/webform/reservation_de_table/confirmation', '/form/reservation-de-table/confirmation', 'und'),
(107, '/node/153', '/hotel/5/le-bristol', 'en'),
(108, '/node/154', '/hotel/5/la-villa-florentine', 'en'),
(109, '/node/155', '/hotel/5/hotel-du-palais', 'en'),
(110, '/node/156', '/hotel/5/le-meurice', 'en'),
(111, '/node/157', '/hotel/4/hotel-de-seze', 'en'),
(112, '/node/158', '/hotel/3/hotel-albert-1er', 'en'),
(113, '/node/160', '/restaurant/epicure', 'en'),
(114, '/node/161', '/restaurant/flocon-de-sel', 'en'),
(115, '/node/162', '/restaurant/le-jardin-des-sens', 'en'),
(116, '/node/163', '/restaurant/le-meurice-alain-ducasse', 'en');
