
-- --------------------------------------------------------

--
-- Structure de la table `d8_sessions`
--

DROP TABLE IF EXISTS `d8_sessions`;
CREATE TABLE IF NOT EXISTS `d8_sessions` (
  `uid` int(10) UNSIGNED NOT NULL COMMENT 'The d8_users.uid corresponding to a session, or 0 for anonymous user.',
  `sid` varchar(128) CHARACTER SET ascii NOT NULL COMMENT 'A session ID (hashed). The value is generated by Drupal''s session handlers.',
  `hostname` varchar(128) CHARACTER SET ascii NOT NULL DEFAULT '' COMMENT 'The IP address that last used this session ID (sid).',
  `timestamp` int(11) NOT NULL DEFAULT '0' COMMENT 'The Unix timestamp when this session last requested a page. Old records are purged by PHP automatically.',
  `session` longblob COMMENT 'The serialized contents of $_SESSION, an array of name/value pairs that persists across page requests by this session ID. Drupal loads $_SESSION from here at the start of each request and saves it at the end.',
  PRIMARY KEY (`sid`),
  KEY `timestamp` (`timestamp`),
  KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Drupal''s session handlers read and write into the sessions…';

--
-- Déchargement des données de la table `d8_sessions`
--

INSERT INTO `d8_sessions` (`uid`, `sid`, `hostname`, `timestamp`, `session`) VALUES
(1, 'OjM_Y2oTG-y0LsFkNbwnbWcj2IfyswO_4Xg_puffzo4', '::1', 1518097531, 0x5f7366325f617474726962757465737c613a313a7b733a333a22756964223b733a313a2231223b7d5f7366325f666c61736865737c613a303a7b7d5f7366325f6d6574617c613a343a7b733a313a2275223b693a313531383039373530353b733a313a2263223b693a313531373931303336343b733a313a226c223b733a373a2232303030303030223b733a313a2273223b733a34333a226b2d75516d6a4d4a726d6c6931794b504a716e4c3047494c706c6171555575496f3359753977714d6f4167223b7d617574686f72697a655f706167655f7469746c657c4f3a34383a2244727570616c5c436f72655c537472696e675472616e736c6174696f6e5c5472616e736c617461626c654d61726b7570223a333a7b733a393a22002a00737472696e67223b733a31343a22557064617465206d616e61676572223b733a31323a22002a00617267756d656e7473223b613a303a7b7d733a31303a22002a006f7074696f6e73223b613a303a7b7d7d);
